fix: layout on ssr
spryker/oryx pull request #1018
Opened 2023-12-19 11:26 UTC by supproduction

2023-12-20 07:12 UTC, tobi-or-not-tobi commented
The initial rendering looks good, but the links to products are broken, both from carousel as well as from search

2023-12-20 07:14 UTC, tobi-or-not-tobi requested changes
The initial rendering looks good, but the links to products are broken, both from carousel as well as from search

2023-12-21 09:23 UTC, dunqan approved these changes

2023-12-21 09:37 UTC, tobi-or-not-tobi approved these changes

2023-12-21 09:38 UTC, merged