chore: vite and vitest versions
spryker/oryx pull request #15
Opened 2023-02-15 09:34 UTC by galitskye

closes [HRZ-2109](https://spryker.atlassian.net/browse/HRZ-2109)

2023-02-15 12:02 UTC, AndreyYevtukhov requested changes

2023-02-15 12:02 UTC, AndreyYevtukhov commented on libs/domain/user/address-edit/src/address-edit.component.spec.ts
> +  describe.skip('when submit throws an error', () => {
If it can't be fixed - let's create a bug ticket and let's add it into current Sprint so that we don't miss it

2023-02-15 12:03 UTC, supproduction submitted a review, later dismissed

2023-02-16 13:20 UTC, AndreyYevtukhov commented on libs/domain/user/address-edit/src/address-edit.component.spec.ts
> +  describe.skip('when submit throws an error', () => {
covered by https://spryker.atlassian.net/browse/HRZ-2277

2023-02-16 13:21 UTC, AndreyYevtukhov submitted a review, later dismissed
Disabled test is covered by https://spryker.atlassian.net/browse/HRZ-2277

2023-02-21 08:35 UTC, supproduction approved these changes

2023-02-23 11:52 UTC, merged