feat: child hydration before hydration of main element
spryker/oryx pull request #226
Opened 2023-04-02 23:39 UTC by supproduction

fixes hydration flickering 

closes [HRZ-2614](https://spryker.atlassian.net/browse/HRZ-2614)

2023-04-05 07:12 UTC, dunqan commented on libs/base/utilities/src/decorators/hydratable/hydratable.ts
>        setTimeout(() => {
all this logic should only happen on clientside, yes?

2023-04-05 07:12 UTC, dunqan commented on libs/base/ui/structure/text/src/text.component.ts
> +        <slot></slot>
We dropped reacting on `slotchange` event here. Are we safe? maybe @tobi-or-not-tobi can you take a look at this one?

2023-04-05 09:30 UTC, supproduction commented on libs/base/utilities/src/decorators/hydratable/hydratable.ts
>        setTimeout(() => {
we don't trigger this on client side. But agree

2023-04-05 10:11 UTC, tobi-or-not-tobi requested changes

2023-04-05 10:11 UTC, tobi-or-not-tobi commented on libs/base/ui/structure/text/src/text.component.ts
> +      !this.resizeObserver
let's leave this to the setup method maybe?

2023-04-05 10:11 UTC, tobi-or-not-tobi commented on libs/base/ui/structure/text/src/text.component.ts
> +        <slot></slot>
yes, we have an alternative implementation using the lifecycle method

2023-04-05 10:11 UTC, tobi-or-not-tobi commented on libs/base/ui/structure/text/src/text.component.ts
> +      !this.resizeObserver
```
if (!this.truncateAfter || !this.resizeObserver) this.truncation = false;
```

2023-04-05 10:11 UTC, tobi-or-not-tobi commented on libs/base/ui/structure/text/src/text.component.ts
> +    }
nitpick: we could simplify as `this.style.removeProperty('--line-clamp', null);` should remove the property afaik

2023-04-07 10:01 UTC, tobi-or-not-tobi approved these changes

2023-04-07 10:14 UTC, merged