feat: navigation components stories
spryker/oryx pull request #250
Opened 2023-04-06 15:10 UTC by Sinucid

Storybook stuff for navigation item and button components. Also styles were aligned according to current designs

closes to [HRZ-2394](https://spryker.atlassian.net/browse/HRZ-2394)

2023-04-06 16:22 UTC, tobi-or-not-tobi requested changes

2023-04-06 16:22 UTC, tobi-or-not-tobi commented on libs/domain/site/navigation-button/src/navigation-button.component.ts
Did we not say NavigationLinkCompnonent?

2023-04-06 16:22 UTC, tobi-or-not-tobi commented on libs/domain/site/navigation-button/src/navigation-button.component.ts
Also, do we still support max badge number in the cart (i.e. 99+)?

2023-04-07 06:07 UTC, Sinucid commented on libs/domain/site/navigation-button/src/navigation-button.component.ts
Nope, we we discussing proper name for auth login link, but not this guy. 

Regarding badge - this is supported on resolvers level (by hardcoded way, but still)

2023-04-07 09:48 UTC, tobi-or-not-tobi approved these changes

2023-04-07 09:52 UTC, merged