feat: oryx-search small screens behaviour
spryker/oryx pull request #303
Opened 2023-04-26 15:15 UTC by Sinucid

On screens smaller then 769px input becomes floated and it's visibility controls by icon-button

closes to [HRZ-2734](https://spryker.atlassian.net/browse/HRZ-2734)

2023-04-26 20:04 UTC, tobi-or-not-tobi requested changes
Nice work. The floating search box is not visible due to a clash with css specificity since the not-floating selector was added.

2023-04-26 20:04 UTC, tobi-or-not-tobi commented on libs/base/ui/form/select/src/stories/select-demo.stories.ts
> +    options: ['prefix', 'suffix', 'none'],
we better use `SearchIconPosition` here

2023-04-26 20:04 UTC, tobi-or-not-tobi commented on libs/base/ui/search/searchbox/src/searchbox.component.ts
> +  @property({ attribute: 'not-floated' }) notFloated?: boolean;
what about `float = true`?

2023-04-26 20:04 UTC, tobi-or-not-tobi commented on libs/base/ui/search/searchbox/src/searchbox.component.ts
> +  @property({ attribute: 'not-floated' }) notFloated?: boolean;
also, let's add `type: Boolean`

2023-04-27 06:49 UTC, Sinucid commented on libs/base/ui/search/searchbox/src/searchbox.component.ts
> +  @property({ attribute: 'not-floated' }) notFloated?: boolean;
`xs-floated` and turned off by default

2023-04-27 07:14 UTC, tobi-or-not-tobi approved these changes

2023-04-27 07:59 UTC, merged