feat: picking lists header (WIP)
spryker/oryx pull request #307
Opened 2023-04-28 13:15 UTC by Sinucid

closes to [HRZ-2732](https://spryker.atlassian.net/browse/HRZ-2732)

2023-05-03 08:10 UTC, gund requested changes

2023-05-03 08:10 UTC, gund commented on libs/domain/picking/src/components/picking-lists-header/picking-lists-header.component.ts
> +    console.log(value);
Remove? 😊

2023-05-03 08:10 UTC, gund commented on libs/domain/picking/src/components/picking-lists-header/picking-lists-header.component.ts
> +        @oryx.close=${() => console.log('close')}
?

2023-05-03 08:21 UTC, Sinucid commented on libs/domain/picking/src/components/picking-lists-header/picking-lists-header.component.ts
> +    console.log(value);
Placeholder, because logic will be added later

2023-05-03 08:22 UTC, Sinucid commented on libs/domain/picking/src/components/picking-lists-header/picking-lists-header.component.ts
> +        @oryx.close=${() => console.log('close')}
The same, temporary part

2023-05-03 09:29 UTC, nsilva-spryker requested changes
Looks good!
Just some small design glitches:
![Screenshot 2023-05-03 at 10 28 19](https://user-images.githubusercontent.com/105730125/235880255-6db50917-c38f-4996-a9d2-439cd694284c.png)

![Screenshot 2023-05-03 at 10 28 06](https://user-images.githubusercontent.com/105730125/235880238-3f0e10d4-19e3-49ee-a98a-64d7f0d9d0ce.png)

2023-05-03 09:38 UTC, Sinucid reviewed
@nsilva-spryker This feature of `oryx-search` with button and floating inputs works only for small screens. For desktops it is just an ordinary input, thats why I can look glitchy on big screens, but it is not a case for FA due it it is mobile only for now

2023-05-03 16:54 UTC, nsilva-spryker commented on libs/domain/picking/src/components/picking-lists-header/picking-lists-header.component.ts
> +    console.log(value);
yup, this will be handy to implement logic: https://spryker.atlassian.net/browse/HRZ-2733

2023-05-03 16:58 UTC, nsilva-spryker approved these changes
Floated input position fixed. thks

2023-05-04 09:12 UTC, gund approved these changes

2023-05-04 09:13 UTC, gund commented on libs/domain/picking/src/components/picking-lists-header/picking-lists-header.component.ts
> +    console.log(value);
Ok for the future better to just add TODO comments so it's clear that this is intentional 👌

2023-05-04 14:19 UTC, Sinucid commented on libs/domain/picking/src/components/picking-lists-header/picking-lists-header.component.ts
> +    console.log(value);
Sure, thanks for advice

2023-05-05 06:23 UTC, merged