feat: style fulfillment login page
spryker/oryx pull request #313
Opened 2023-05-02 09:42 UTC by aleespryker

Closes [HRZ-2821](https://spryker.atlassian.net/browse/HRZ-2821)

2023-05-02 13:31 UTC, Sinucid requested changes

2023-05-02 13:31 UTC, Sinucid commented on libs/base/ui/form/input/src/form-control/floating-label.styles.ts
> +  const floatParentheses = unsafeCSS(attribute ? '([floatLabel])' : '');
Both consts are similar, why are they separate values?

2023-05-02 13:31 UTC, Sinucid commented on libs/domain/picking/src/components/login/login.component.spec.ts
> +    expect(element.renderRoot.querySelector('oryx-auth-login')).not.toBeNull();
`expect(element).toContainElement('oryx-auth-login');`

2023-05-02 13:31 UTC, Sinucid commented on libs/domain/picking/src/components/login/login.component.spec.ts
> +    expect(element.renderRoot.querySelector('oryx-image')).not.toBeNull();
`expect(element).toContainElement('oryx-image');`

2023-05-02 13:31 UTC, Sinucid commented on libs/domain/picking/src/components/login/login.component.spec.ts
> +    expect(element.renderRoot.querySelector('oryx-heading')).not.toBeNull();
`expect(element).toContainElement('oryx-heading');`

2023-05-02 13:31 UTC, Sinucid commented on libs/domain/picking/src/components/login/login.component.ts
> +        options="${JSON.stringify({ enableRememberMe: false })}"
Stringify, why?

2023-05-02 13:31 UTC, Sinucid commented on libs/platform/auth/src/components/login/login.styles.ts
> +    gap: var(--login-gap, 18px);
Do we need specific css var for this? Maybe just ordinary `--gap`?

2023-05-02 13:31 UTC, Sinucid commented on libs/platform/auth/src/components/login/login.styles.ts
> +    margin: var(--button-margin, 0);
Looks like component specific variable.  `--_login-button-margin`

2023-05-02 14:30 UTC, aleespryker commented on libs/base/ui/form/input/src/form-control/floating-label.styles.ts
> +  const floatParentheses = unsafeCSS(attribute ? '([floatLabel])' : '');
Because they showed up multiple times in the styles where we have `:host([floatLabel])` and because `:host()` is invalid syntax.

2023-05-02 14:33 UTC, aleespryker commented on libs/domain/picking/src/components/login/login.component.ts
> +        options="${JSON.stringify({ enableRememberMe: false })}"
Because the object by itself didn't work: `options="${{ enableRememberMe: false }}"`` or even `options=${{ enableRememberMe: false}}`

2023-05-02 14:45 UTC, aleespryker commented on libs/platform/auth/src/components/login/login.styles.ts
> +    margin: var(--button-margin, 0);
Do you mean `--_margin`? It's only affecting the button padding, not the margin.

2023-05-02 15:07 UTC, Sinucid commented on libs/base/ui/form/input/src/form-control/floating-label.styles.ts
> +  const floatParentheses = unsafeCSS(attribute ? '([floatLabel])' : '');
Oh, sorry. I missed additional brackets.

2023-05-02 15:14 UTC, Sinucid commented on libs/platform/auth/src/components/login/login.styles.ts
> +    margin: var(--button-margin, 0);
I meant we should make it's name less common and add some components-related emphasis. `--button-margin` is too common and can be accidentally overriden in the future

2023-05-02 15:17 UTC, Sinucid commented on libs/domain/picking/src/components/login/login.component.ts
> +        options="${JSON.stringify({ enableRememberMe: false })}"
Left a comment then, please, that should be refactored after EB integration

2023-05-02 15:26 UTC, Sinucid commented on libs/domain/picking/src/components/login/login.component.ts
> +        options="${JSON.stringify({ enableRememberMe: false })}"
Probably, because there need to use dot binding: `.options="${{ enableRememberMe: false }}"`

2023-05-03 14:48 UTC, Sinucid requested changes
Some inputs still have glitches, quantity-input for example

2023-05-05 13:17 UTC, Sinucid submitted a review, later dismissed

2023-05-05 14:29 UTC, Sinucid approved these changes

2023-05-05 14:32 UTC, merged