[WIP] refactor: site refactor
spryker/oryx pull request #346
Opened 2023-05-16 18:30 UTC by tolerants

- [x] Prefix the component selector with oryx
- [ ] Avoid using RxJS operators inside components
  - [ ] oryx-site-navigation-item
  - [ ] oryx-site-notification-center
- [x] Use signals (computed, effect, signalProperty) instead of asyncValue
  - [x] oryx-site-locale-selector
  - [x] oryx-site-currency-selector
  - [x] oryx-site-navigation-item
- [x] Add component schema’s
- [ ] Add defaultOptions
- [ ] (Not relevant) Use command / queries in domain logic services
- [x] Drop src folder for components
- [x] Move components to the package src folder

2023-05-18 21:40 UTC, tobi-or-not-tobi requested changes

2023-05-18 21:40 UTC, tobi-or-not-tobi commented on libs/domain/site/src/components/locale-selector/index.ts
we need to export the schema file as well

2023-05-18 21:40 UTC, tobi-or-not-tobi commented on libs/domain/site/src/components/locale-selector/locale-selector.model.ts
the model is empty, let's drop it

2023-05-18 21:40 UTC, tobi-or-not-tobi commented on libs/domain/site/src/components/locale-selector/locale-selector.model.ts
same in other components

2023-05-18 21:40 UTC, tobi-or-not-tobi commented on libs/domain/site/src/components/notification-center/notification-center.component.ts
>  @defaultOptions({
use `autoCloseTime` rather than `defaultAutoCloseTime`

2023-05-18 21:40 UTC, tobi-or-not-tobi commented on libs/domain/site/src/components/notification-center/notification-center.component.ts
>  @defaultOptions({
We should also use effect or computed rather than subscribe

2023-05-18 21:40 UTC, tobi-or-not-tobi commented on libs/domain/site/src/components/navigation-item/navigation-item.component.ts
> +    return badge ? this.tokenResolver.resolveToken(badge) : null;
```suggestion
    const badge = this.$options().badge;
    return badge ? this.tokenResolver.resolveToken(badge) : null;
```

2023-05-18 21:40 UTC, tobi-or-not-tobi commented on libs/domain/site/src/components/navigation-item/navigation-item.component.ts
> +    return label ? this.tokenResolver.resolveToken(label) : null;
```suggestion
    const label = this.$options().label;
    return label ? this.tokenResolver.resolveToken(label) : null;
```

2023-05-18 21:40 UTC, tobi-or-not-tobi commented on libs/domain/site/src/components.def.ts
> +export * from './components/currency-selector/currency-selector.def';
what about moving this file into components and import it in `feature.ts`?

`/site/src/components/def.ts`

2023-05-19 15:47 UTC, tobi-or-not-tobi commented on libs/domain/site/src/components.def.ts
> +export * from './components/currency-selector/currency-selector.def';
You need to update the file, as the links are broken

2023-05-24 12:43 UTC, supproduction requested changes, later dismissed

2023-05-24 12:43 UTC, supproduction commented on libs/domain/site/src/components/locale-selector/locale-selector.component.ts
> +          this.locales() ?? [],
Can we move default value into signal?

2023-05-24 12:43 UTC, supproduction commented on libs/domain/site/src/components/date/date.schema.ts
> +  options: {},
We can drop `options`

2023-05-24 12:43 UTC, supproduction commented on libs/domain/site/src/components/navigation-button/navigation-button.schema.ts
> +    options: {},
We can drop options

2023-05-24 12:43 UTC, supproduction commented on libs/domain/site/src/components/price/price.schema.ts
> +  options: {},
Do we need options?

2023-05-24 19:12 UTC, tobi-or-not-tobi requested changes

2023-05-24 19:12 UTC, tobi-or-not-tobi commented on libs/domain/site/src/components/notification-center/notification-center.component.ts
>      const { position, enableStacking } = this.componentOptions ?? {};
```suggestion
    const { position, enableStacking } = this.$options();
```

2023-05-24 19:12 UTC, tobi-or-not-tobi commented on libs/domain/site/src/components/locale-selector/locale-selector.schema.ts
>      group: 'Site',
```suggestion
    group: 'Site',
    icon: 'language',
```

2023-05-24 19:12 UTC, tobi-or-not-tobi commented on libs/domain/site/src/components/price/price.schema.ts
> +  group: 'Site',
```suggestion
  group: 'Site',
  icon: 'currency_exchange',
```

2023-05-24 19:12 UTC, tobi-or-not-tobi commented on libs/domain/site/src/components/currency-selector/currency-selector.schema.ts
>      group: 'Site',
```suggestion
    group: 'Site',
    icon: 'euro',
```

2023-05-24 19:12 UTC, tobi-or-not-tobi commented on libs/domain/site/src/components/date/date.schema.ts
> +  group: 'Site',
```suggestion
  group: 'Site',
  icon: 'event',
```

2023-05-24 20:12 UTC, tobi-or-not-tobi approved these changes, later dismissed

2023-05-25 07:37 UTC, supproduction approved these changes, later dismissed

2023-05-25 09:50 UTC, supproduction submitted a review, later dismissed

2023-06-01 07:30 UTC, tobi-or-not-tobi approved these changes

2023-06-01 07:34 UTC, dunqan approved these changes

2023-06-05 07:12 UTC, merged