feat: add e2e tests for picking lists search functionality
spryker/oryx pull request #349
Opened 2023-05-17 14:21 UTC by nsilva-spryker

Add e2e tests for picking lists search functionality.
Refactor proper header title.

Close [HRZ-2825](https://spryker.atlassian.net/browse/HRZ-2825)

2023-05-18 17:03 UTC, AndreyYevtukhov commented on apps/fulfillment-e2e/src/integration/picking-lists-search.cy.ts
> +      .should('contain.text', 'Search by order ID');
In the future, we might have to update this text, and if we keep it in code and in the e2e test -> we will have to update both places

We can replace it with a visibility check to make it more stable

2023-05-18 17:05 UTC, AndreyYevtukhov commented on apps/fulfillment-e2e/src/integration/picking-lists-search.cy.ts
> +      });
This check can also be replaced with a visibility check, because we already select an element by a placeholder (https://github.com/spryker/oryx/pull/349/files#diff-43c0002f2468bbe3b6e7b0e6f3fbd1b98e220dac8ebf622310399ca2b38de4d2R4), and then check the same placeholder - which does not add value to the test

2023-05-18 17:08 UTC, AndreyYevtukhov commented on apps/fulfillment-e2e/src/integration/picking-lists-search.cy.ts
> +  it('should check success search flow', () => {
What about

```
it('should show correct picking items after search')
```
?)

2023-05-18 17:10 UTC, AndreyYevtukhov requested changes
Left small suggestions

2023-05-19 12:14 UTC, AndreyYevtukhov commented on apps/fulfillment-e2e/src/integration/picking-lists-search.cy.ts
> +      .should('contain.text', 'Search by order ID');
text check left here

2023-05-19 12:14 UTC, AndreyYevtukhov commented on apps/fulfillment-e2e/src/integration/picking-lists-search.cy.ts
> +      .should('contain.text', 'No picking results');
and here

2023-05-19 12:15 UTC, AndreyYevtukhov requested changes, later dismissed
2 super small leftovers

2023-05-19 15:39 UTC, gund approved these changes

2023-05-19 16:16 UTC, merged