fix: correct sorting order
spryker/oryx pull request #353
Opened 2023-05-22 11:25 UTC by aleespryker

Closes [HRZ-2918](https://spryker.atlassian.net/browse/HRZ-2918)

2023-05-22 12:03 UTC, gund requested changes

2023-05-22 12:03 UTC, gund commented on libs/domain/picking/src/services/adapter/picking-list-default.adapter.ts
> +      ),
Please remove duplicated `itemsCount` parsing logic from the `PickingListOnlineDefaultAdapter` and `PickingListOffline`.
https://github.com/spryker/oryx/blob/a61711e1a09df11c5210b2888d7f3469faadeb40/libs/domain/picking/offline/services/adapter/picking-list-online-default.adapter.ts#L86-L89
https://github.com/spryker/oryx/blob/a61711e1a09df11c5210b2888d7f3469faadeb40/libs/domain/picking/offline/entities/picking-list.entity.ts#L74

2023-05-24 08:26 UTC, Sinucid approved these changes

2023-05-24 09:10 UTC, gund approved these changes

2023-05-24 11:01 UTC, merged