feat: extract customer note modal in separate component
spryker/oryx pull request #406
Opened 2023-06-01 11:03 UTC by tarashaliuk

Extracted customer note modal in separate component and used it in the header component
closes: [HRZ-2922](https://spryker.atlassian.net/browse/HRZ-2922)

2023-06-01 13:54 UTC, Sinucid requested changes

2023-06-01 13:54 UTC, Sinucid commented on libs/base/ui/action/icon-button/src/icon-button.styles.ts
> +    color: var(--oryx-button-color, var(--oryx-color-neutral-11));
You can control color of the icon by `--oryx-icon-color` css var. Just apply in the styles

2023-06-01 13:54 UTC, Sinucid commented on libs/domain/picking/src/components/customer-note-modal/customer-note-modal.component.ts
> +        @oryx.close=${this.close}
`oryx.close` is bubbling up, this is not necessary

2023-06-01 13:54 UTC, Sinucid commented on libs/domain/picking/src/components/picking-header/picking-header.component.spec.ts
> +import { beforeEach } from 'vitest';
not needed

2023-06-01 13:54 UTC, Sinucid commented on libs/domain/picking/src/components/picking-header/picking-header.component.ts
> +          <oryx-customer-note-modal
```
    ${when(this.pickingList?.cartNote && this.isCartNoteVisible, () => 
      html`<oryx-customer-note-modal
        .note=${this.pickingList.cartNote}
        @oryx.close=${() => (this.isCartNoteVisible = false)}
      ></oryx-customer-note-modal>`
    )}
    
```

2023-06-01 13:54 UTC, gund commented on libs/domain/picking/src/components/customer-note-modal/customer-note-modal.component.ts
> +  @property() note?: string;
Why not making note a slot?
Also it will be easier to have `open` property in the same way that standard modal has it so it's similar to work with.

2023-06-01 16:56 UTC, tarashaliuk commented on libs/domain/picking/src/components/picking-header/picking-header.component.ts
> +          <oryx-customer-note-modal
Implemented modal opening as @gund suggested - using the "open" attribute. Not sure that now we need the `when` directive - at least to reduce the initial number of rendered HTML.

2023-06-02 06:19 UTC, Sinucid requested changes

2023-06-02 06:19 UTC, Sinucid commented on libs/base/ui/action/icon-button/src/icon-button.styles.ts
> +    --oryx-icon-color: var(--oryx-color-neutral-11);
No, this is not what I meant. You do not need to make any changes in this component, if you need to change it's color just set this css var in the styles where this is necessary, like there:

`oryx-icon-button {
    --oryx-icon-color: red;
}`

2023-06-02 08:39 UTC, Sinucid approved these changes

2023-06-02 08:44 UTC, gund approved these changes

2023-06-02 09:42 UTC, merged