feature: implement fulfillment user navigation item
spryker/oryx pull request #408
Opened 2023-06-01 15:33 UTC by aleespryker

Closes [HRZ-2896](https://spryker.atlassian.net/browse/HRZ-2896)

2023-06-02 13:47 UTC, Sinucid requested changes

2023-06-02 13:47 UTC, Sinucid commented on libs/base/ui/overlays/modal/src/modal.styles.ts
> +    font-weight: var(--oryx-header-font-weight);
Need to align with Nuwan and justify designs for modal component

2023-06-02 13:47 UTC, Sinucid commented on libs/domain/picking/src/components/picking-header/picking-header.component.ts
> +      <oryx-picking-user-navigation-item> </oryx-picking-user-navigation-item>`;
use ordinary `oryx-site-navigation-item`

2023-06-02 13:47 UTC, Sinucid commented on libs/domain/picking/src/components/user-navigation-item/user-navigation-item.component.ts
> +        fullscreen: true,
not needed. Will be the standard behaviour of modal component for small screens

2023-06-02 13:47 UTC, Sinucid commented on libs/domain/picking/src/components/user-navigation-item/user-navigation-item.component.ts
> +        heading: i18n('oryx.picking.account'),
use label instead and update navigation item component to make it use label as heading for the modal

2023-06-02 13:47 UTC, Sinucid commented on libs/domain/site/navigation-item/src/navigation-item.styles.ts
> +    --oryx-icon-color: var(--oryx-color-neutral-11);
not needed. Will be updated with adding the semantic types for icon buttons

2023-06-02 14:01 UTC, gund approved these changes, later dismissed

2023-06-02 14:05 UTC, Sinucid commented on libs/domain/picking/src/components/user-navigation-item/user-navigation-item.component.ts
> +        fullscreen: true,
You can just hardcode fullscreen attr on oryx-modal inside navigation-item for now

2023-06-06 11:49 UTC, Sinucid approved these changes

2023-06-06 12:04 UTC, merged