feat: first scratch to add user profile logic and content
spryker/oryx pull request #438
Opened 2023-06-12 12:25 UTC by supproduction

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2023-06-12 16:10 UTC, gund requested changes

2023-06-12 16:10 UTC, gund commented on libs/domain/picking/offline/services/adapter/bapi-push-notification-default.adapter.spec.ts
> +import { PickingHttpService } from '../../../src/services';
`offline` is a secondary entry point and it cannot import stuff from main entry point using relative paths, it should always import stuff from the package name.
What should be fixed is internal imports in the `offline` modules which import other `offline` modules - those should be relative. This also should be fixed in the `.spec` files of the `offline` modules.

2023-06-13 07:53 UTC, tolerants commented
It's a `chore`, not `fix`.

2023-06-14 08:20 UTC, closed without merging

2023-06-14 08:21 UTC, nsilva-spryker commented
Changes apply on `offline` module on: https://github.com/spryker/oryx/pull/422