feat: implement references component
spryker/oryx pull request #454
Opened 2023-06-14 09:38 UTC by tarashaliuk

DRAFT PR
closes: [HRZ-2838](https://spryker.atlassian.net/browse/HRZ-2838)

2023-06-14 12:16 UTC, tobi-or-not-tobi requested changes

2023-06-14 12:16 UTC, tobi-or-not-tobi commented on libs/domain/product/references/src/references.component.ts
> +export class ReferencesComponent extends ProductMixin(LayoutMixin(LitElement)) {
```suggestion
export class ProductReferencesComponent extends ProductMixin(LayoutMixin(LitElement)) {
```

2023-06-14 12:16 UTC, tobi-or-not-tobi commented on libs/domain/product/references/src/references.component.ts
> +      ? this.alternativeProductsListService.get(this.$product()!.sku!)
what about:

```ts
const sku = this.$product()?.sku;
return sku ? this.alternativeProductsListService.get(sku) : of(undefined);
``

2023-06-14 12:16 UTC, tobi-or-not-tobi commented on libs/domain/product/references/src/references.component.ts
> +  protected list = computed(() => {
```suggestion
  protected $list = computed(() => {
```

we just agreed on a new convention to prefix both computed and signals with a dollar.

2023-06-14 12:16 UTC, tobi-or-not-tobi commented on libs/domain/product/src/services/adapter/alternative-products-list.adapter.ts
> +  get(sku: string): Observable<Product[]>;
Can we use a qualifier instead? we like to avoid many arguments and rather pass qualifier objects through all layers. With that, we can extend qualifiers and do not need to change all application layers to bring in new things. 

This will allow to bring in component options going forward to query alternative alternatives - say up sell vs cross sell vs spair parts, etc.

2023-06-14 12:16 UTC, tobi-or-not-tobi commented on libs/domain/product/src/services/adapter/default-alternative-products-list.adapter.ts
> +      .pipe(this.transformer.do(AlternativeProductsListNormalizer));
can we not use the default product (list) normalizer?

2023-06-14 15:21 UTC, tarashaliuk commented on libs/domain/product/src/services/adapter/default-alternative-products-list.adapter.ts
> +      .pipe(this.transformer.do(AlternativeProductsListNormalizer));
The `ProductListNormalizer` is incompletable with the alternative products list data structure. The `AlternativeProductsListNormalizer` uses the `ProductNormalizer` inside

2023-06-16 08:27 UTC, tobi-or-not-tobi approved these changes

2023-06-16 08:28 UTC, merged