chore: checkout UI
spryker/oryx pull request #459
Opened 2023-06-15 06:52 UTC by tobi-or-not-tobi

The new checkout designs require a “step” header. We move this into a separate component to allow for consistent styling as well as moving to collapsible headers in the future.

closes [HRZ-3067](https://spryker.atlassian.net/browse/HRZ-3067)

2023-06-15 08:10 UTC, supproduction requested changes

2023-06-15 08:10 UTC, supproduction commented on libs/domain/checkout/shipping-method/shipping-method.styles.ts
> +  } */
do we need it?

2023-06-15 08:15 UTC, supproduction submitted a review, later dismissed

2023-06-15 13:20 UTC, tolerants commented
We are providing several new components - how ot can be `chore`?

2023-06-15 13:27 UTC, tolerants commented on libs/domain/checkout/header/header.component.ts
> +    return html` <slot></slot>`;
```suggestion
    return html`<slot></slot>`;
```

2023-06-19 12:39 UTC, supproduction approved these changes

2023-06-19 12:40 UTC, merged