feat: link component storefront styles
spryker/oryx pull request #485
Opened 2023-06-21 05:39 UTC by tobi-or-not-tobi

Refactored the component and introduced standard link styles.

2023-06-21 07:00 UTC, Sinucid requested changes

2023-06-21 07:00 UTC, Sinucid commented on libs/domain/content/link/link.component.ts
> +    const { label, target } = this.$options();
```suggestion
    const { label, target, icon, button } = this.$options();
```

2023-06-21 07:00 UTC, Sinucid commented on libs/domain/content/link/link.component.ts
> +    const icon = this.$options().button && this.$options().icon;
```suggestion
    const renderIcon = button && icon;
```

2023-06-21 07:00 UTC, Sinucid commented on libs/domain/content/link/link.component.ts
> +            () => html`<oryx-icon .type=${this.$options().icon}></oryx-icon>`
```suggestion
            renderIcon,
            () => html`<oryx-icon .type=${icon}></oryx-icon>`
```

2023-06-21 07:00 UTC, Sinucid commented on libs/domain/content/link/link.component.ts
> +        href=${this.$link()}
Should we not render the anchor if link === null?

2023-06-21 07:00 UTC, Sinucid commented on libs/domain/content/link/link.model.ts
> +  params?: Record<string, string>;
Docs?

2023-06-21 07:00 UTC, Sinucid commented on libs/platform/experience/src/color/colors/gray/gray.ts
> +    // 0: 'hsl(0, 0%, 100.0%)',
leftover?

2023-06-21 07:00 UTC, Sinucid commented on libs/platform/experience/src/color/colors/gray/gray.ts
> +    // 0: 'hsl(0, 0%, 0%)',
the same

2023-06-21 07:10 UTC, tobi-or-not-tobi commented on libs/domain/content/link/link.model.ts
> +  params?: Record<string, string>;
we likely do another refactor on those, so I left docs out for now

2023-06-21 13:19 UTC, Sinucid requested changes

2023-06-21 13:19 UTC, Sinucid commented on libs/base/ui/action/link/src/link.component.ts
> +    this.toggleAttribute('has-icon', !!value);
Why do you need this setter? Just to set the 'has-icon' attr? Try the selector like `[icon]:not([icon=""])`

2023-06-22 06:37 UTC, Sinucid approved these changes, later dismissed

2023-06-23 07:10 UTC, Sinucid approved these changes

2023-06-23 07:11 UTC, merged