feat(i18n): add support for links in translations
spryker/oryx pull request #492
Opened 2023-06-22 08:21 UTC by gund

- [x] Add transformation of links to a default `i18nInjectable`
- [x] Add support for HTML in `i18n` directive
- [ ] Implement unit tests

2023-06-23 12:01 UTC, supproduction requested changes

2023-06-23 12:01 UTC, supproduction commented on libs/base/utilities/src/directives/i18n/i18n.directive.ts
> +  return html`${unsafeHTML(text)}`;
Do we need separate function for it?

2023-06-23 12:01 UTC, supproduction commented on libs/platform/i18n/project.json
> +      }
why do we need it? 
we can just use `--watch`

2023-06-26 08:11 UTC, gund commented on libs/base/utilities/src/directives/i18n/i18n.directive.ts
> +  return html`${unsafeHTML(text)}`;
Yeah I previously had 2 places where I was using it but after refactoring it's not needed so will remove it 👌

2023-06-26 08:12 UTC, gund commented on libs/platform/i18n/project.json
> +      }
Well I'm using NX Console extension to launch nx commands and it does not support writing extra flags so it's nice to have a shortcut to be able to launch watch mode in one click 😊

2023-06-26 08:51 UTC, supproduction submitted a review, later dismissed

2023-06-26 10:46 UTC, dunqan submitted a review, later dismissed

2023-06-26 18:04 UTC, dunqan approved these changes, later dismissed

2023-06-27 08:32 UTC, dunqan approved these changes

2023-06-27 08:38 UTC, merged