test
spryker/oryx pull request #564
Opened 2023-07-06 08:54 UTC by supproduction

<Please include a summary of the changes>

closes: <Add a Jira ticket link(s) here>

BREAKING CHANGE: <Add a description of breaking change, if any. If none - remove this line completely>

---

### Checklist before requesting a code review

- [ ] PR title is aligned with [PR titles and conventional commits](https://spryker.atlassian.net/wiki/spaces/FA/pages/3821175291/PR+titles+and+conventional+commits)
- [ ] I have performed a self-review of my code and have fixed all jobs failures

2023-07-06 10:06 UTC, tobi-or-not-tobi requested changes

2023-07-06 10:06 UTC, tobi-or-not-tobi commented on libs/template/application/lambda/src/handler.lambda.ts
> +  ttl?: number;
Is this number in milliseconds? Or years? can we add a doc on that?

2023-07-11 10:17 UTC, tobi-or-not-tobi requested changes

2023-07-11 10:17 UTC, tobi-or-not-tobi commented on apps/storefront/server/hosting/netlify.ts
> +    ttl: 900,
Now that we have our builders cache sorted, we can actually drop the value here. It's still cool to have the feature available, but for our dev env we do not need it I'd say.

2023-07-11 10:26 UTC, tobi-or-not-tobi approved these changes

2023-07-11 10:27 UTC, dunqan approved these changes

2023-07-11 10:50 UTC, merged