fix: log out button displays loading indicator when clicked
spryker/oryx pull request #565
Opened 2023-07-06 10:29 UTC by aleespryker

closes: [HRZ-3197](https://spryker.atlassian.net/browse/HRZ-3197)

---

### Checklist before requesting a code review

- [ ] PR title is aligned with [PR titles and conventional commits](https://spryker.atlassian.net/wiki/spaces/FA/pages/3821175291/PR+titles+and+conventional+commits)
- [ ] I have performed a self-review of my code and have fixed all jobs failures

2023-07-06 15:51 UTC, supproduction requested changes

2023-07-06 15:51 UTC, supproduction commented on libs/domain/picking/user-profile/user-profile.component.ts
>      this.authService.logout();
Is it possible to get error on logout func?
Should we change `logoutLoading` to false then?

2023-07-10 08:40 UTC, Sinucid requested changes

2023-07-10 08:40 UTC, Sinucid commented on libs/domain/picking/user-profile/user-profile.component.spec.ts
> +        ).not.toBeNull();
```suggestion
        expect(element).toContainElement('oryx-button[loading]');
```

2023-07-10 08:40 UTC, Sinucid commented on libs/domain/picking/user-profile/user-profile.component.ts
> +  protected logoutLoading: boolean | null = null;
```suggestion
  protected logoutLoading = false;
```

2023-07-10 08:44 UTC, Sinucid requested changes

2023-07-10 08:44 UTC, Sinucid commented on libs/domain/picking/user-profile/user-profile.component.spec.ts
> +
and also would be nice to test error handling

2023-07-10 12:18 UTC, Sinucid approved these changes

2023-07-10 12:38 UTC, supproduction approved these changes

2023-07-10 12:39 UTC, merged