chore: picking lists loading indicator
spryker/oryx pull request #691
Opened 2023-08-04 09:27 UTC by aleespryker

WIP

closes: [HRZ-89545](https://spryker.atlassian.net/browse/HRZ-89545)

2023-08-11 08:33 UTC, supproduction reviewed
Please, change the title to `feat(picking)...`

2023-08-11 08:33 UTC, supproduction commented on libs/domain/picking/picking-lists/picking-lists.component.ts
> +  protected injector = resolve(INJECTOR);
do we need this injector?

2023-08-11 08:33 UTC, supproduction commented on libs/domain/picking/picking-lists/picking-lists.component.ts
> +        ></span>`,
```suggestion
        () => html`<span class="sync">
        <span>${i18n('picking.loading-data')}</span>
          <oryx-spinner></oryx-spinner>
          </span>`,
```

2023-08-11 09:29 UTC, nsilva-spryker requested changes
Looks good. Small comments

2023-08-11 09:29 UTC, nsilva-spryker commented on libs/domain/picking/offline/services/picking-sync-action-handler.service.spec.ts
> +      expect(callback).toHaveBeenCalledWith(false);
This seems ambiguous, is true and false at the same time

2023-08-11 09:29 UTC, nsilva-spryker commented on libs/domain/picking/offline/services/picking-sync-action-handler.service.ts
> +        this.syncing$.next(false);
should we put it on tap, in case of error

2023-08-11 11:05 UTC, nsilva-spryker approved these changes

2023-08-15 07:52 UTC, supproduction approved these changes

2023-08-15 14:08 UTC, merged