feat(presets): breadcrumbs storefront integration and e2es
spryker/oryx pull request #722
Opened 2023-08-23 07:11 UTC by Sinucid

- breadcrumbs component added to the search, category and product pages with dynamic visibility rules to hide it on small screens
- added e2e tests coverage for appropriate pages

closes: [HRZ-2318](https://spryker.atlassian.net/browse/HRZ-2318), [HRZ-89604](https://spryker.atlassian.net/browse/HRZ-89604)

2023-08-24 12:12 UTC, tobi-or-not-tobi submitted a review, later dismissed
I have missed the previous PRs due to holidays, but have a few comments on this work:
- can we rename to breadcrumb? (singular)
- the last part of the breadcrumb should have an `inert` attribute to ensure it's not accessible
- we need to use standard font based icons for storefront. Let's use `chevron_right` or `navigate_next` for the delimiter. 
- I'd drop the `showDivider` and allow to have a nullish `divider` option that steers the usage of divider icon in the first place. 
- can we get an optional icon per breadcrumb? So that we can have the home icon to start the breadcrumb with, it's a common practice. Other pages could also add an icon in between, but that's not so common. Making it part of the breadcrumb parts, ensures it's clickable.
- Can we get the product category/ies in the pdp breadcrumb? Ideally we track the categories from the URL or history, but if not provided, we should rely on the product data. We have categories integrated in product data nowadays. 

We can address this feedback in separate subtask(s).

2023-08-24 12:12 UTC, tobi-or-not-tobi commented on libs/template/presets/storefront/experience/pages/search-page.ts
> +      id: 'breadcrumbs',
can we leave out the `id`?

2023-08-25 12:56 UTC, supproduction requested changes

2023-08-25 12:56 UTC, supproduction commented on apps/storefront-e2e/src/support/page-fragments/breadcrumbs.fragment.ts
> +  nthBreadcrumb = (n: number) => this.get().find(`a:nth-of-type(${n})`);
can we use nthBreadcrumb(-1) for last element?
`this.get().find('a').eq(number) `

2023-08-25 12:56 UTC, supproduction commented on apps/storefront-e2e/src/support/page-fragments/breadcrumbs.fragment.ts
> +    const link = this.get().find('a:first-of-type');
```suggestion
    const link = this.nthBreadcrumb('1');
```

2023-08-25 12:56 UTC, supproduction commented on apps/storefront-e2e/src/support/page-fragments/breadcrumbs.fragment.ts
> +    link.invoke('attr', 'href').should('eq', '/');
```suggestion
    link.should('contain.text', 'Home').invoke('attr', 'href').should('eq', '/');
```

2023-08-25 12:56 UTC, supproduction commented on libs/domain/product/src/services/routes.ts
> +];
just add it to the product routes

2023-08-25 13:34 UTC, supproduction approved these changes

2023-08-25 14:27 UTC, merged