Remove patch on cart when changing price mode
spryker/oryx pull request #748
Opened 2023-09-06 16:37 UTC by nsilva-spryker

Requirements have change regarding price mode patch update. Right now **we will not patch cart with price mode**

2023-09-06 17:44 UTC, supproduction requested changes

2023-09-06 17:44 UTC, supproduction commented on libs/domain/cart/src/services/adapter/default-cart.adapter.ts
> -  update(data: UpdateCartQualifier): Observable<Cart> {
I would keep update method, just delete headers

2023-09-06 17:44 UTC, supproduction commented on libs/domain/cart/src/services/default-cart.service.ts
> -  protected updatePriceMode$ = createEffect<Cart>([
Let's create update method in service

2023-09-07 07:32 UTC, supproduction requested changes

2023-09-07 07:32 UTC, supproduction commented on libs/domain/cart/src/services/cart.providers.ts
> -  },
Also, please delete interceptor from public API? (means export)

2023-09-07 07:34 UTC, supproduction requested changes

2023-09-07 07:34 UTC, supproduction commented on libs/domain/cart/src/services/default-cart.service.ts
> +          take(1),
Please, use similar flow as `addEntry...`

2023-09-07 09:29 UTC, nsilva-spryker commented on libs/domain/cart/src/services/cart.providers.ts
> -  },
`export const PriceModeChangeGuard = 'oryx.PriceModeChangeGuard*'`
Was deleted from file `price-mode.service.ts`

2023-09-07 11:05 UTC, supproduction approved these changes

2023-09-07 11:07 UTC, merged