chore(picking): refactor picking component names
spryker/oryx pull request #759
Opened 2023-09-12 14:37 UTC by aleespryker

closes: [HRZ-89742](https://spryker.atlassian.net/browse/HRZ-89742)

BREAKING CHANGE: Picking components are now labelled differently.

eg, `<oryx-customer-note></oryx-customer-note>` is now `<oryx-picking-customer-note></oryx-picking-customer-note>` according to our components naming conventions.

2023-09-13 08:03 UTC, tolerants commented
It's not a breaking change as long as this module is not release yet.

2023-09-14 10:45 UTC, Sinucid requested changes

2023-09-14 10:45 UTC, Sinucid commented on apps/fulfillment-e2e/src/support/page_fragments/picking-in-progress-modal.fragment.ts
> +  getWrapper = () => cy.get('oryx-picking-picking-in-progress-modal');
I believe we can make and exception here, because **picking-picking** looks not very impressive

2023-09-14 10:45 UTC, Sinucid commented on libs/domain/picking/customer-note-modal/customer-note-modal.def.ts
>  export const customerNoteModalComponent = componentDef({
Each components class name, def funcs, schema should start with domain name, ie: `pickingCustomerNoteModalComponent`, `PickingCustomerNoteModalComponent`

Double check, please, other components and make re-namings

2023-09-18 06:38 UTC, Sinucid requested changes
Additional changes, that I would like to ask you to make:

- PickingListMixinInterface implements interface from picking-lists component ( PickingListComponentProperties ), that is ridiculous. Move it, please, to the src/models
- login and picker components have default exports, that looks strange and unreasonable. Drop them, please, and use exported classes directly

2023-09-18 10:49 UTC, Sinucid approved these changes, later dismissed

2023-09-20 14:05 UTC, tolerants requested changes

2023-09-20 14:05 UTC, tolerants commented on libs/domain/picking/login/login.def.ts
> +export const pickingLoginPageComponent = componentDef({
```suggestion
export const pickingLoginComponent = componentDef({
```

2023-09-20 14:05 UTC, tolerants commented on libs/domain/picking/login/login.component.ts
> +export class PickingLoginPageComponent extends I18nMixin(LitElement) {
```suggestion
export class PickingLoginComponent extends I18nMixin(LitElement) {
```

2023-09-20 14:11 UTC, Sinucid submitted a review, later dismissed

2023-09-20 14:39 UTC, Sinucid requested changes

2023-09-20 14:39 UTC, Sinucid commented on libs/domain/picking/login/login.component.spec.ts
>  describe('LoginPageComponent', () => {
```suggestion
describe('PickingLoginComponent', () => {
```

2023-09-22 08:33 UTC, tolerants approved these changes

2023-09-22 08:39 UTC, Sinucid approved these changes

2023-09-22 09:29 UTC, merged