fix(test): improve search e2e stability
spryker/oryx pull request #765
Opened 2023-09-13 17:29 UTC by Sinucid

no ticket yet

2023-09-15 06:11 UTC, AndreyYevtukhov commented on apps/storefront-e2e/src/integration/search.cy.ts
> -      searchPage.waitForSearchRequest();
Why we are removing this wait? 

Without it we might have false positives here

2023-09-17 06:23 UTC, AndreyYevtukhov requested changes
left 1 comment, let's double check if that removal is required (and why it worked before)

2023-09-18 12:50 UTC, tolerants commented
It's not a `fix`, but `test` type.

2023-09-21 06:18 UTC, AndreyYevtukhov approved these changes

2023-09-21 06:34 UTC, merged