fix(order): display delivery costs in order page
spryker/oryx pull request #787
Opened 2023-09-20 15:48 UTC by aleespryker

closes: [HRZ-89892](https://spryker.atlassian.net/browse/HRZ-89892)

2023-09-20 16:36 UTC, supproduction requested changes

2023-09-20 16:36 UTC, supproduction commented on libs/domain/order/src/services/totals/order-totals.resolver.ts
> +          shipmentTotal: shipments?.[0].defaultGrossPrice,
But if we in the Net mode?

2023-09-22 08:13 UTC, Sinucid approved these changes

2023-09-26 08:07 UTC, supproduction approved these changes

2023-09-26 08:46 UTC, merged