feat: impemented addditional requirements for facet rating component
spryker/oryx pull request #816
Opened 2023-10-10 14:53 UTC by tarashaliuk

Implemented additional requirements that were described [here](https://spryker.atlassian.net/browse/HRZ-1947?focusedCommentId=428481)

closes: https://spryker.atlassian.net/browse/HRZ-1947

2023-10-10 16:01 UTC, tobi-or-not-tobi requested changes
Can we introduce the removal of this buried rating facet with featureVersion flag?

2023-10-10 16:01 UTC, tobi-or-not-tobi commented on libs/domain/search/facet-rating/facet-rating.component.ts
> +  max: 4,
should we keep min to 1 min? We can change it to `0` and it creates an additional non-star

2023-10-10 16:01 UTC, tobi-or-not-tobi commented on libs/domain/search/facet-rating/facet-rating.component.ts
> +    }
```suggestion
  protected renderValueControlLabel(facetValue: FacetValue): TemplateResult | void {
    const { scale } = this.$options();

    if (!scale) return;
```

2023-10-10 16:01 UTC, tobi-or-not-tobi commented on libs/domain/search/facet-rating/facet-rating.component.ts
> +          () => html`<span>& up</span>`
let's use i18n here. we do not need to mimic the `&` in the code, let's add a translation in labs package though.

2023-10-10 16:01 UTC, tobi-or-not-tobi commented on libs/domain/search/facet-rating/facet-rating.model.ts
> +   * Indicates the scale for a rating facet.
What does scale mean? can we elaborate in the docs here?

2023-10-11 07:02 UTC, tarashaliuk commented on libs/domain/search/facet-rating/facet-rating.component.ts
> +  max: 4,
Do you mean to create options validation that will block using the wrong values like `0`, `-1`  for `min` and other validations to rest options?

2023-10-11 08:09 UTC, tobi-or-not-tobi commented on libs/domain/search/facet-rating/facet-rating.component.ts
> +  max: 4,
yes, or gracefully change to min 1. But i'm not sure if there are negative consequences tbh

2023-10-11 13:02 UTC, tarashaliuk commented on libs/domain/search/facet-rating/facet-rating.component.ts
> +    }
It is overridden method so we can't change the return type

2023-10-11 13:47 UTC, tobi-or-not-tobi requested changes

2023-10-11 13:47 UTC, tobi-or-not-tobi commented on libs/domain/search/facet-rating/facet-rating.component.ts
> +          () => html`<span>${this.i18n('& up')}</span>`
```suggestion
          () => html`<span>${this.i18n('search.facet.rating.up')}</span>`
```

We should add an entry at `libs/template/labs/src/i18n/translations/en.ts` with the translated `& up`.

2023-10-11 14:33 UTC, tobi-or-not-tobi approved these changes

2023-10-11 15:10 UTC, merged