test: facet rating e2e tests
spryker/oryx pull request #821
Opened 2023-10-12 17:06 UTC by tarashaliuk

Added e2e tests for rating component and fixed empty facet bug

closes: https://spryker.atlassian.net/browse/HRZ-89609

2023-10-13 06:52 UTC, AndreyYevtukhov requested changes
Found some leftovers, let's remove those

2023-10-13 06:52 UTC, AndreyYevtukhov commented on apps/storefront-e2e/src/integration/category.cy.ts
> +  // describe('Products sorting', () => {
??

2023-10-13 06:52 UTC, AndreyYevtukhov commented on apps/storefront-e2e/src/integration/search.cy.ts
> +  // describe('Products sorting', () => {
??

2023-10-17 09:29 UTC, AndreyYevtukhov approved these changes

2023-10-17 12:24 UTC, tobi-or-not-tobi approved these changes

2023-10-17 14:11 UTC, merged