[WIP] feat: pluggable layouts
spryker/oryx pull request #846
Opened 2023-10-26 13:40 UTC by supproduction

adds pluggable layouts

2023-11-06 13:17 UTC, tobi-or-not-tobi requested changes

2023-11-06 13:17 UTC, tobi-or-not-tobi commented on libs/platform/experience/src/services/layout/plugins/styles/layout/layout-style.schema.ts
> +  name: 'misc',
```suggestion
  name: 'Layout',
```

2023-11-06 13:17 UTC, tobi-or-not-tobi commented on libs/platform/experience/src/services/layout/plugins/styles/spacing/spacing-style.schema.ts
> +  name: 'layout',
```suggestion
  name: 'spacing',
```

2023-11-07 08:06 UTC, Sinucid commented on libs/platform/experience/layout/layout.component.spec.ts
>  });
```suggestion
  describe('when the version >= 1.2', () => {
    beforeEach(async () => {
      mockFeatureVersion('1.2');
      
      mockLayoutService.getStyles.mockReturnValue(of('stylesResult'));
      mockLayoutService.getStylesFromOptions.mockReturnValue(
        of('inlineResult')
      );
      element = await fixture(html`<oryx-layout layout="grid"></oryx-layout>`);
    });

    it('should render style tag with content from service', () => {
      const style = element.renderRoot.querySelector('style');
      expect(style?.textContent).toContain('stylesResult');
      expect(style?.textContent).toContain('inlineResult');
    });
  });
});
```

2023-11-07 08:06 UTC, Sinucid commented on libs/platform/experience/src/controllers/layout.controller.ts
> +          .replace(/-([a-z])/g, (g) => g[1].toUpperCase());
Can we use just `toUpperCase` ?

```suggestion
        const prop = attr.replace('layout-', '').toUpperCase();
```

2023-11-07 08:06 UTC, Sinucid commented on libs/platform/experience/src/controllers/layout.controller.ts
> +  }
```suggestion
  protected parseAttribute(
    attribute: string | null
  ): string | boolean | number {
    if (attribute === null || attribute === 'false') return false;
    if (!isNaN(parseFloat(attribute))) return parseFloat(attribute);
    if (attribute === 'true') return true;

    return attribute || true;
  }
```

2023-11-07 08:06 UTC, Sinucid commented on libs/platform/experience/src/mixins/layout.mixin.ts
> +   * Use attributes with the same name but together with layout prefix instead.
Maybe better to add an example of the attribute instead of long description?

2023-11-07 08:06 UTC, Sinucid commented on libs/platform/experience/src/services/data-client/revealers/layout/layout-experience-data.revealer.ts
> +
```suggestion
      const layout: LayoutStylesOptions = selectedLayout ?
        typeof selectedLayout === 'string' ? { type: selectedLayout }: selectedLayout:
        {};
```

2023-11-07 08:06 UTC, Sinucid commented on libs/platform/experience/src/services/layout/default-layout.builder.ts
> +        return styles === '' ? undefined : styles;
```suggestion
        return style || undefined;
```

2023-11-07 08:06 UTC, Sinucid commented on libs/platform/experience/src/services/layout/plugins/types/column/column-layout.model.ts
> +    column: undefined;
undefined?

2023-11-07 09:22 UTC, supproduction commented on libs/platform/experience/src/controllers/layout.controller.ts
> +          .replace(/-([a-z])/g, (g) => g[1].toUpperCase());
we transform it to camelCase

2023-11-07 09:23 UTC, supproduction commented on libs/platform/experience/src/controllers/layout.controller.ts
> +  }
improved

2023-11-07 09:23 UTC, supproduction commented on libs/platform/experience/src/mixins/layout.mixin.ts
> +   * Use attributes with the same name but together with layout prefix instead.
not sure

2023-11-07 09:25 UTC, supproduction commented on libs/platform/experience/src/services/data-client/revealers/layout/layout-experience-data.revealer.ts
> +
why it's better?

2023-11-07 09:28 UTC, supproduction commented on libs/platform/experience/src/services/layout/plugins/types/column/column-layout.model.ts
> +    column: undefined;
we need only key from this interface as then we transform it to union type
<img width="620" alt="image" src="https://github.com/spryker/oryx/assets/16482929/13d433b1-a3c6-41bf-90dd-f111209647c8">

2023-11-07 09:43 UTC, Sinucid commented on libs/platform/experience/src/services/data-client/revealers/layout/layout-experience-data.revealer.ts
> +
At least a bit more readable. In your variant the fallback value (empty object) is a part of condition falsy branch. 
And another thing, my variant is covering additional case when `selectedLayout === ''`, and prevent getting of `{type: ''}`

2023-11-07 09:46 UTC, Sinucid submitted a review, later dismissed

2023-11-07 09:53 UTC, supproduction commented on libs/platform/experience/src/services/data-client/revealers/layout/layout-experience-data.revealer.ts
> +
Not sure regarding redability. and if `selectedLayout === ''` we anyway have to transform it to object
<img width="481" alt="image" src="https://github.com/spryker/oryx/assets/16482929/c25809d0-55b1-49dc-ac59-2d4be3be3e0a">

2023-11-07 13:22 UTC, tobi-or-not-tobi approved these changes

2023-11-07 13:41 UTC, merged