[WIP]
spryker/oryx pull request #850
Opened 2023-10-27 19:38 UTC by supproduction

<Please include a summary of the changes>

closes: <Add a Jira ticket link(s) here>

BREAKING CHANGE: <Add a description of breaking change, if any. If none - remove this line completely>

2023-10-30 07:55 UTC, tobi-or-not-tobi commented on libs/platform/experience/src/services/layout/index.ts
> +export * from './layout-styles.utilities';
seems we're missing plugins here

2023-10-30 12:14 UTC, supproduction commented on libs/platform/experience/src/services/layout/index.ts
> +export * from './layout-styles.utilities';
we have it on line 8

2023-10-30 15:30 UTC, tobi-or-not-tobi requested changes

2023-10-30 15:30 UTC, tobi-or-not-tobi commented on libs/platform/experience/src/mixins/layout.mixin.ts
> +    protected screen$ = computed(
```suggestion
    protected $screen = computed(
```

2023-10-30 15:30 UTC, tobi-or-not-tobi commented on libs/platform/experience/src/services/layout/plugins/properties/sticky/sticky-layout.plugin.ts
> +    });
I thought we're going to have the ability to resolve the schema properties from this plugin as well as from other plugins.

2023-10-30 15:30 UTC, tobi-or-not-tobi commented on libs/platform/experience/src/services/layout/plugins/styles/typography/typography-layout.plugin.ts
> +  }
The typography related model would ideally move out of the `composition.model.ts` and find home here in the model/schema.

2023-10-30 16:02 UTC, tobi-or-not-tobi requested changes

2023-10-30 16:02 UTC, tobi-or-not-tobi commented on libs/platform/experience/src/services/layout/plugins/styles/misc/misc-layout.model.ts
> +    zIndex?: number;
let's move it to sticky plugin.

2023-10-30 16:02 UTC, tobi-or-not-tobi commented on libs/platform/experience/src/services/layout/plugins/styles/misc/misc-layout.model.ts
> +    columnCount?: number;
`columnCount`, `align`, `justify`, `span`, `colSpan`, `rowSpan`, `gridRow`, `gridColumn` and `gap` are all related to layout. Used by many layouts. Could we move them to a layout style plugin? Or can we use them in different layout plugins (e.g. column, carousel and grid)? In the latter case, they would be used multiple times.

2023-10-30 16:02 UTC, tobi-or-not-tobi commented on libs/platform/experience/src/services/layout/plugins/styles/misc/misc-layout.model.ts
> +    overflow?: string;
let's move to sticky

2023-10-30 16:02 UTC, tobi-or-not-tobi commented on libs/platform/experience/src/services/layout/plugins/styles/misc/misc-layout.model.ts
> +    background?: string;
let's move background, fill, border and radius to `canvas` styles plugin. We might come with a better name over time. We're on our way to eliminate `misc`.

2023-10-31 05:28 UTC, tobi-or-not-tobi requested changes

2023-10-31 05:28 UTC, tobi-or-not-tobi commented on libs/platform/experience/src/services/layout/plugins/styles/canvas/canvas-style.model.ts
> +    columnCount?: number;
layout related styles are not expected here

2023-10-31 05:28 UTC, tobi-or-not-tobi commented on libs/platform/experience/src/services/layout/layout.model.ts
>      vertical?: boolean;
This one could move to LayoutStyles

2023-10-31 05:28 UTC, tobi-or-not-tobi commented on libs/platform/experience/src/services/layout/layout.model.ts
>    export interface LayoutsProperty {
Should we name it `LayoutProperty`?

2023-10-31 05:28 UTC, tobi-or-not-tobi commented on libs/platform/experience/src/services/layout/plugins/properties/divider/divider-layout.plugin.ts
>      return ssrAwaiter(import('./divider.styles').then((m) => m.styles));
What about renaming the styles `dividerStyles` and export the styles in `index.ts`?

2023-10-31 05:28 UTC, tobi-or-not-tobi commented on libs/platform/experience/src/services/layout/plugins/properties/divider/divider-layout.plugin.ts
>      return ssrAwaiter(import('./divider.styles').then((m) => m.styles));
if we do this, we should do it everywhere

2023-10-31 05:28 UTC, tobi-or-not-tobi commented on libs/platform/experience/src/services/layout/plugins/styles/canvas/canvas-style.schema.ts
> +];
not in use

2023-10-31 05:28 UTC, tobi-or-not-tobi commented on libs/platform/experience/src/services/layout/plugins/styles/canvas/canvas-style.model.ts
> +    ratio?: string;
we have this one also at spacing model

2023-10-31 08:51 UTC, tobi-or-not-tobi commented on libs/platform/experience/src/services/layout/layout.model.ts
>      vertical?: boolean;
Where do we render the vertical property?

2023-10-31 10:34 UTC, tobi-or-not-tobi approved these changes

2023-10-31 10:49 UTC, merged