feat: add sf e2e tests
spryker/oryx pull request #96
Opened 2023-03-01 19:07 UTC by AndreyYevtukhov

2023-03-02 20:11 UTC, supproduction requested changes

2023-03-02 20:11 UTC, supproduction commented on apps/storefront-e2e/src/types/product.type.ts
> +export type Product = {
Why we can't use types from packages?

2023-03-02 20:11 UTC, supproduction commented on apps/storefront-e2e/project.json
> +      }
I would suggest use it as separate targets, cause we do like this everywhere

2023-03-02 20:11 UTC, supproduction commented on apps/storefront-e2e/project.json
> +      }
And command shorter then

2023-03-02 20:11 UTC, supproduction commented on package.json
> +    "sf:e2e:headless:ci:affected": "npx nx print-affected --select=projects | grep -E 'storefront' && npm run sf:e2e:headless:ci",
Why do we need `npx` here?

2023-03-02 20:11 UTC, supproduction commented on package.json
> +    "sf:e2e:headless:ci:affected": "npx nx print-affected --select=projects | grep -E 'storefront' && npm run sf:e2e:headless:ci",
you can use `run-p` instead of `concurrently` and delete this new dep

2023-03-03 09:59 UTC, AndreyYevtukhov commented on apps/storefront-e2e/project.json
> +      }
but in the case of separate targets, we will have a lot of copy-pasted code (as we do now)
I had an issue with that 3 times so far, and decided to do it NX way (which actually should be used everywhere) :)

2023-03-03 10:03 UTC, AndreyYevtukhov commented on package.json
> +    "sf:e2e:headless:ci:affected": "npx nx print-affected --select=projects | grep -E 'storefront' && npm run sf:e2e:headless:ci",
> Why do we need npx here? 

I use it everywhere to run packages - why should we NOT use it?)

2023-03-03 10:18 UTC, AndreyYevtukhov commented on package.json
> +    "sf:e2e:headless:ci:affected": "npx nx print-affected --select=projects | grep -E 'storefront' && npm run sf:e2e:headless:ci",
What is `run-p`? (I see that it was last updated 7 years ago, so I'm not quite sure that it is usable - https://npmtrends.com/concurrently-vs-npm-run-all-vs-run-p-vs-run-parallel-vs-wsrun)

---

And why should we replace the `concurrently` package? 

It does everything we need here: 

- parallel tasks execution
- nice useful logs
- correct process killing and handling
- the ability to manage exit codes (which is used in CI) etc. 

It is actively supported and does not have security issues - so I can't understand what is the problem here and why it should be changed (and why we should spend hours again debugging and configuring this flow with a new tool like `run-p` or something if we already have a working solution) :)

2023-03-03 10:21 UTC, AndreyYevtukhov commented on apps/storefront-e2e/src/types/product.type.ts
> +export type Product = {
I'm not quite sure what you mean here(( 

These types are used only for **E2E test data** and are not related to frontend types or API responses

I can change the name to `ProductTestData` or something to make it more precise. Should I do it?

2023-03-03 13:04 UTC, supproduction commented on apps/storefront-e2e/src/types/product.type.ts
> +export type Product = {
Better change it

2023-03-03 13:07 UTC, supproduction commented on apps/storefront-e2e/project.json
> +      }
I am not against that to change it everywhere. I am against that this one will be not the same as others. If we have an issue we need ticket to fix it

2023-03-03 13:07 UTC, supproduction commented on package.json
> +    "sf:e2e:headless:ci:affected": "npx nx print-affected --select=projects | grep -E 'storefront' && npm run sf:e2e:headless:ci",
You need just script which will run processes in parallel. We already have this, why do we need new dep?

2023-03-03 14:10 UTC, AndreyYevtukhov commented on apps/storefront-e2e/project.json
> +      }
https://spryker.atlassian.net/browse/HRZ-2363 - refactoring ticket

2023-03-03 14:16 UTC, AndreyYevtukhov commented on package.json
> +    "sf:e2e:headless:ci:affected": "npx nx print-affected --select=projects | grep -E 'storefront' && npm run sf:e2e:headless:ci",
https://spryker.atlassian.net/browse/HRZ-2364 - refactoring ticket

2023-03-03 14:48 UTC, AndreyYevtukhov commented on apps/storefront-e2e/src/types/product.type.ts
> +export type Product = {
Done

2023-03-03 14:53 UTC, supproduction approved these changes, later dismissed

2023-03-03 15:32 UTC, supproduction approved these changes

2023-03-03 15:34 UTC, merged